### ISSUE TITLE
(Feature Requests) UI, info bars, menu, adjust profession xp by profession

### ISSUE THREAD

**Issue by archenovalis** [mfoltz/Bloodcraft#34]
I believe the following are necessary and high priority.

1) Add xp needed to next level on HUD
2) Custom window / popup interface showing list of everything's level and xp to next level, and things obtained (profession, prestige, class, blood legacy, familiars obtained, etc)
3) ~~Ability to configure profession xp by profession (ie: harvesting needs to be 0.05 when mining is at 1)~~ #35  
4) Gain xp by level by level difference (1 + (level difference * config value). For example level 1 vs level 10 creature = 1.45x xp and level 10 player vs level 1 creature = 0.55xp (1 + (-9 level diff * 0.05) = 1 + (-0.45) = 0.55)
5) Custom window / popup showing chat commands with descriptions and a button assigned to each.
6) Automate .prepare

**Comment by archenovalis** [comment]
!35 resolves request 3

**Comment by mfoltz** [comment]
1. See Eclipse (test release has link)
2. Will be putting as many features in Eclipse as I can but it’s not easy work and quite time consuming.
3. Appreciate the effort, will review when I get the chance but most likely won’t be making any changes to professions until I have the time do a general revamp.
4. There is a tapering factor for experience gained from low level kills by high level players (LevelScalingMultiplier) that accomplishes the latter well enough. Otherwise providing extra scaling experience for high level kills by low level players is too easy to abuse with feed executes and don’t really have an interest in supporting the extra configuration values or code that would then merit.
5. Will be improving the UI in general but for a variety of factors this would be far more work than it’s worth.
6. Definitely on the todo list.

appreciate the feedback! In the future please reserve GitHub issues for bugs and other problems of that nature. Feature requests and additions are much better off in the modding discord, feel free to ping me there.
